project:
  type: website
  output-dir: docs

lang: es

website:
  title: "NOCTUA+ <img src='images/seo.png' height='50' style='padding-left:30px'><img src='images/uam.png' height='50' style='padding-left:20px'>"
  favicon: "images/favicon.png"
  navbar:
    logo: images/favicon.png
    right:
      - href: index.qmd
        text: Inicio
      - href: proyecto.qmd
        text: El proyecto
      - href: resultados.qmd
        text: Resumen de resultados
      - href: participar.qmd
        text: ¿Cómo participar?
      - href: especies.qmd
        text: Especies de estudio
      - href: equipo.qmd
        text: Equipo

  page-footer:
    center:
      - "© 2026 NOCTUA+<br>Proyecto de colaboración:<br>SEO/BirdLife  |  Universidad Autónoma de Madrid, Departamento de Ecología"
    background: light

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    include-after-body: buho.html
    grid:
      margin-width: 300px
    self-contained: false

resources:
  - images

editor: visual

