name: Deploy docs to public repo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Deploy docs to public repo
        run: |
          cd docs
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Deploy site"

          git branch -M main

          git push --force https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/noctua-mas/web.git main
