name: Build and deploy Quarto site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Deploy to public repo
        run: |
          cd docs
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Deploy site"

          git branch -M main

          git push --force https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/noctua-mas/web.git main
